In [1]:
from ukbeaver import tabular

ph = tabular.Phenotype('/home/yuruize/reborn/ukbeaver/data/participant_pheno.tsv')

In [2]:
import polars as pl

df = pl.read_csv(
    ph.supplement_table,
    separator="\t",
    ignore_errors=True,
    infer_schema_length=0,  # Scan more rows for type inference
    # truncate_ragged_lines=True,  # Truncate extra columns in ragged rows
    # quote_char='"',  # Assume double-quotes if any are present
    # has_header=True
)
print(df.shape)  # Should now match or be closer to Pandas' 11,825

(11825, 29)

sys:1: UserWarning: CSV malformed: expected 263 rows, actual 1549 rows, in chunk starting at byte offset 273414, length 520576
sys:1: UserWarning: CSV malformed: expected 1492 rows, actual 1526 rows, in chunk starting at byte offset 1834795, length 520354

In [2]:
import polars as pl
import pandas as pd

# --- Polars read ---
df_polars = pl.read_csv(
    ph.supplement_table,
    separator="\t",
    ignore_errors=True,
    truncate_ragged_lines=True,
    infer_schema_length=0,
).select(["field_id", "value_type"])

# --- Pandas read ---
df_pandas = pd.read_csv(
    ph.supplement_table,
    sep="\t",
    usecols=["field_id", "value_type"],
    dtype=str  # avoid type mismatch issues
)

sys:1: UserWarning: CSV malformed: expected 1492 rows, actual 1526 rows, in chunk starting at byte offset 1834795, length 520354
sys:1: UserWarning: CSV malformed: expected 263 rows, actual 1549 rows, in chunk starting at byte offset 273414, length 520576

In [3]:
# Convert Polars → pandas
df_polars_pd = df_polars.to_pandas()

# Fill NaN and cast everything to string for consistency
df_polars_pd = df_polars_pd.fillna("").astype(str)
df_pandas = df_pandas.fillna("").astype(str)

In [4]:
import numpy as np

same_shape = df_polars_pd.shape == df_pandas.shape
same_content = df_polars_pd.equals(df_pandas)

print("Same shape:", same_shape)
print("Completely identical:", same_content)

Same shape: True
Completely identical: True

In [3]:
import warnings
import polars as pl

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message="CSV malformed")
    df = pl.read_csv(
        ph.supplement_table,
        separator="\t",
        ignore_errors=True,
        truncate_ragged_lines=True,
        columns=["field_id", "value_type"],
        infer_schema_length=0,
    )

In [3]:
df.select(["field_id", "value_type"])

shape: (11_825, 2)
┌──────────┬────────────┐
│ field_id ┆ value_type │
│ ---      ┆ ---        │
│ i64      ┆ i64        │
╞══════════╪════════════╡
│ 3        ┆ 11         │
│ 4        ┆ 11         │
│ 5        ┆ 11         │
│ 6        ┆ 11         │
│ 19       ┆ 21         │
│ …        ┆ …          │
│ 2032154  ┆ 41         │
│ 2032155  ┆ 41         │
│ 2032156  ┆ 41         │
│ 2032157  ┆ 41         │
│ 2032158  ┆ 41         │
└──────────┴────────────┘

In [4]:
df

shape: (10_505, 2)
┌──────────┬────────────┐
│ field_id ┆ value_type │
│ ---      ┆ ---        │
│ str      ┆ str        │
╞══════════╪════════════╡
│ 3        ┆ 11         │
│ 4        ┆ 11         │
│ 5        ┆ 11         │
│ 6        ┆ 11         │
│ 19       ┆ 21         │
│ …        ┆ …          │
│ 2032154  ┆ 41         │
│ 2032155  ┆ 41         │
│ 2032156  ┆ 41         │
│ 2032157  ┆ 41         │
│ 2032158  ┆ 41         │
└──────────┴────────────┘